version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: neuroflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: neuroflow_admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password_123
      MONGO_INITDB_DATABASE: neuroflow_db
    volumes:
      - mongodb-data:/data/db
    networks:
      - neuroflow-network

  mongo-express:
    image: mongo-express:latest
    container_name: neuroflow-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: neuroflow_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secure_password_123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: hackathon2025
    depends_on:
      - mongodb
    networks:
      - neuroflow-network

volumes:
  mongodb-data:

networks:
  neuroflow-network:
    driver: bridge
